"use client";

import { DrashButton } from "@/components/ui/DrashButton";
import {
  DrashCard,
  DrashCardContent,
  DrashCardHeader,
} from "@/components/ui/DrashCard";
import { createClient } from "@/lib/supabase/client";
import { cn } from "@/lib/utils/utils";
import {
  Book,
  CheckCircle2,
  ChevronRight,
  Database,
  FolderOpen,
  Languages,
  Play,
  Search,
} from "lucide-react";
import { useMemo, useState } from "react";

// Importing the discovery data generated by our crawler scripts
import sefariaRegistry from "@/lib/etl/sefaria_structured_index.json";

/**
 * Ingest Orchestrator (v3.4 - Null Safe)
 * Filepath: app/admin/ingest/page.tsx
 * Role: Advanced admin tool to browse and sync manuscripts from Sefaria.
 * Fix: Resolved 'toLowerCase' crash by adding defensive null-checks during filtering.
 */

interface Manuscript {
  book: string;
  slug: string;
  language: string;
  version: string;
  categories: string[];
  parentFolder: string;
  githubPath: string;
  rawUrl: string;
}

interface RegistryData {
  timestamp: string;
  total_count: number;
  index: Manuscript[];
}

interface IngestStats {
  bookTitle: string;
  totalVerses: number;
  currentProgress: number;
  status: "idle" | "fetching" | "ingesting" | "completed" | "error";
}

export default function IngestPage() {
  const supabase = createClient();

  // UI State
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedParentFolder, setSelectedParentFolder] = useState<
    string | null
  >(null);
  const [hebrewVersion, setHebrewVersion] = useState<Manuscript | null>(null);
  const [englishVersion, setEnglishVersion] = useState<Manuscript | null>(null);
  const [log, setLog] = useState<string[]>([]);
  const [stats, setStats] = useState<IngestStats>({
    bookTitle: "",
    totalVerses: 0,
    currentProgress: 0,
    status: "idle",
  });

  // 1. Tiered Performance Logic
  const groupedRegistry = useMemo(() => {
    const registry = (sefariaRegistry as unknown as RegistryData) || {
      index: [],
    };
    const foldersMap = new Map<string, Manuscript[]>();
    const index = registry.index || [];

    index.forEach((item: Manuscript) => {
      // Defensive check for folder path existence
      const path = item.parentFolder || "Uncategorized";
      if (!foldersMap.has(path)) {
        foldersMap.set(path, []);
      }
      foldersMap.get(path)!.push(item);
    });

    return Array.from(foldersMap.entries()).map(([path, versions]) => ({
      path,
      versions,
    }));
  }, []);

  // Step B: Filter with strict null-safety
  const bookFolders = useMemo(() => {
    const query = searchQuery.toLowerCase();
    const filtered = groupedRegistry.filter((f) => {
      // Fix: Added optional chaining and fallbacks to prevent 'toLowerCase' on undefined
      const pathMatch = (f.path || "").toLowerCase().includes(query);
      const bookMatch = (f.versions[0]?.book || "")
        .toLowerCase()
        .includes(query);
      return pathMatch || bookMatch;
    });

    return filtered.slice(0, 100);
  }, [groupedRegistry, searchQuery]);

  const addLog = (msg: string) =>
    setLog((prev) =>
      [`[${new Date().toLocaleTimeString()}] ${msg}`, ...prev].slice(0, 12)
    );

  const selectFolder = (folderPath: string, versions: Manuscript[]) => {
    setSelectedParentFolder(folderPath);
    const heb = versions.find((v) => v.language === "Hebrew") || null;
    const eng = versions.find((v) => v.language === "English") || null;
    setHebrewVersion(heb);
    setEnglishVersion(eng);
    addLog(`Target locked: ${versions[0]?.book || "Unknown Book"}`);
  };

  const runIngest = async () => {
    if (!hebrewVersion) return;

    try {
      setStats((prev) => ({
        ...prev,
        status: "fetching",
        bookTitle: hebrewVersion.book,
      }));
      addLog(`Initiating dual-stream ingestion for ${hebrewVersion.book}...`);

      const [hebRes, engRes] = await Promise.all([
        fetch(hebrewVersion.rawUrl).then((r) => r.json()),
        englishVersion
          ? fetch(englishVersion.rawUrl).then((r) => r.json())
          : Promise.resolve(null),
      ]);

      const hebChapters = hebRes.text || [];
      const engChapters = engRes?.text || [];

      setStats((prev) => ({
        ...prev,
        status: "ingesting",
        totalVerses: hebChapters.flat().length,
      }));

      const { data: bookRecord, error: bookError } = await supabase
        .schema("library")
        .from("books")
        .upsert(
          {
            slug: hebrewVersion.slug,
            en_title: hebrewVersion.book,
            he_title: hebRes.heBook || hebrewVersion.book,
            category_path: hebrewVersion.categories.join("/"),
            structure_type: "CHAPTER_VERSE",
          },
          { onConflict: "slug" }
        )
        .select()
        .single();

      if (bookError) throw bookError;

      const batchSize = 40;
      let batch = [];
      let processed = 0;

      for (let cIdx = 0; cIdx < hebChapters.length; cIdx++) {
        const c1 = cIdx + 1;
        const verses = hebChapters[cIdx];
        const engVerses = engChapters[cIdx] || [];

        for (let vIdx = 0; vIdx < verses.length; vIdx++) {
          const c2 = vIdx + 1;
          const ref = `${hebrewVersion.book}.${c1}.${c2}`;

          batch.push({
            book_id: bookRecord.id,
            ref,
            path: `${hebrewVersion.parentFolder.replace(
              /\//g,
              "."
            )}.${c1}.${c2}`.replace(/\s+/g, "_"),
            hebrew_text: verses[vIdx],
            english_text: engVerses[vIdx] || "",
            c1,
            c2,
            c3: 0,
            c4: 0,
            c5: 0,
          });

          if (batch.length >= batchSize) {
            const { error } = await supabase
              .schema("library")
              .from("verses")
              .insert(batch);
            if (error) throw error;
            processed += batch.length;
            setStats((prev) => ({ ...prev, currentProgress: processed }));
            addLog(`Synced through ${ref}`);
            batch = [];
          }
        }
      }

      setStats((prev) => ({ ...prev, status: "completed" }));
      addLog(`Mission Accomplished: ${hebrewVersion.book} indexed.`);
    } catch (err: unknown) {
      const message =
        err instanceof Error ? err.message : "An unexpected error occurred";
      addLog(`FATAL: ${message}`);
      setStats((prev) => ({ ...prev, status: "error" }));
    }
  };

  const registryMetadata = (sefariaRegistry as unknown as RegistryData) || {
    total_count: 0,
  };

  return (
    <div className="max-w-7xl mx-auto p-12 space-y-12 selection:bg-zinc-950 selection:text-white">
      <header className="flex items-end justify-between border-b border-zinc-100 pb-8">
        <div className="space-y-4">
          <div className="flex items-center gap-3 text-amber-500">
            <Database size={24} />
            <span className="text-[10px] font-black uppercase tracking-[0.4em]">
              Administrative Scriptorium
            </span>
          </div>
          <h1 className="text-5xl font-black text-zinc-900 tracking-tighter uppercase italic">
            Ingest Engine v3.0
          </h1>
        </div>
        <div className="flex gap-2">
          <div className="px-4 py-2 bg-zinc-950 text-white rounded-xl text-[10px] font-black uppercase tracking-widest flex items-center gap-3 shadow-xl">
            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            Mirror Synced: {registryMetadata.total_count || 0} Versions
          </div>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-4 space-y-6">
          <div className="relative group">
            <Search
              className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-300 group-focus-within:text-zinc-950 transition-colors"
              size={18}
            />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Filter Registry (e.g. Genesis)..."
              className="w-full pl-12 pr-4 py-4 bg-white border border-zinc-200 rounded-2xl text-sm focus:outline-none focus:ring-8 focus:ring-zinc-950/5 focus:border-zinc-950 transition-all shadow-sm"
            />
          </div>

          <div className="bg-white border border-zinc-100 rounded-[2.5rem] overflow-hidden shadow-sm h-[600px] flex flex-col">
            <div className="p-6 bg-zinc-50 border-b border-zinc-100 flex items-center justify-between">
              <h3 className="text-[10px] font-black text-zinc-400 uppercase tracking-widest flex items-center gap-2">
                <FolderOpen size={14} /> Sefaria Mirror Path
              </h3>
              <span className="text-[9px] font-bold text-zinc-300 uppercase tracking-widest">
                {searchQuery
                  ? `${bookFolders.length} Matches`
                  : `Top ${bookFolders.length}`}
              </span>
            </div>
            <div className="flex-1 overflow-y-auto custom-scrollbar p-2 space-y-1">
              {bookFolders.map((folder) => (
                <button
                  key={folder.path}
                  onClick={() => selectFolder(folder.path, folder.versions)}
                  className={cn(
                    "w-full text-left p-4 rounded-2xl transition-all group",
                    selectedParentFolder === folder.path
                      ? "bg-zinc-950 text-white shadow-xl translate-x-2"
                      : "hover:bg-zinc-50 text-zinc-600"
                  )}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold truncate max-w-[200px]">
                      {folder.path.split("/").pop()}
                    </span>
                    <ChevronRight
                      size={14}
                      className={cn(
                        "transition-transform",
                        selectedParentFolder === folder.path
                          ? "translate-x-1 text-amber-500"
                          : "text-zinc-200"
                      )}
                    />
                  </div>
                  <p
                    className={cn(
                      "text-[9px] uppercase tracking-tighter mt-1 font-medium",
                      selectedParentFolder === folder.path
                        ? "text-zinc-500"
                        : "text-zinc-300"
                    )}
                  >
                    {folder.versions.length} Available Versions
                  </p>
                </button>
              ))}
              {bookFolders.length === 0 && (
                <div className="py-20 text-center text-zinc-300">
                  <p className="text-[10px] font-black uppercase tracking-widest">
                    No matching manuscripts
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="lg:col-span-5 space-y-8">
          <DrashCard className="min-h-[300px]">
            <DrashCardHeader showDivider>
              <div className="flex items-center gap-3">
                <Languages size={18} className="text-zinc-400" />
                <span className="text-[10px] font-black uppercase tracking-widest text-zinc-900">
                  Version Mapping
                </span>
              </div>
            </DrashCardHeader>
            <DrashCardContent className="space-y-10 p-10">
              {selectedParentFolder ? (
                <div className="space-y-8 animate-in fade-in slide-in-from-bottom-2">
                  <div className="space-y-4">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest ml-1">
                      Source (Hebrew)
                    </label>
                    <div className="grid gap-2">
                      {groupedRegistry
                        .find((f) => f.path === selectedParentFolder)
                        ?.versions.filter((v) => v.language === "Hebrew")
                        .map((v) => (
                          <button
                            key={v.githubPath}
                            onClick={() => setHebrewVersion(v)}
                            className={cn(
                              "flex items-center justify-between p-4 rounded-2xl border transition-all",
                              hebrewVersion?.githubPath === v.githubPath
                                ? "bg-amber-50 border-amber-500 text-amber-900 shadow-sm"
                                : "bg-white border-zinc-100 text-zinc-500 hover:border-zinc-300"
                            )}
                          >
                            <span className="text-xs font-bold">
                              {v.version}
                            </span>
                            {hebrewVersion?.githubPath === v.githubPath && (
                              <CheckCircle2 size={14} />
                            )}
                          </button>
                        ))}
                    </div>
                  </div>

                  <div className="space-y-4">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest ml-1">
                      Translation (English)
                    </label>
                    <div className="grid gap-2">
                      {groupedRegistry
                        .find((f) => f.path === selectedParentFolder)
                        ?.versions.filter((v) => v.language === "English")
                        .map((v) => (
                          <button
                            key={v.githubPath}
                            onClick={() => setEnglishVersion(v)}
                            className={cn(
                              "flex items-center justify-between p-4 rounded-2xl border transition-all",
                              englishVersion?.githubPath === v.githubPath
                                ? "bg-blue-50 border-blue-500 text-blue-900 shadow-sm"
                                : "bg-white border-zinc-100 text-zinc-500 hover:border-zinc-300"
                            )}
                          >
                            <span className="text-xs font-bold">
                              {v.version}
                            </span>
                            {englishVersion?.githubPath === v.githubPath && (
                              <CheckCircle2 size={14} />
                            )}
                          </button>
                        ))}
                    </div>
                  </div>
                </div>
              ) : (
                <div className="h-64 flex flex-col items-center justify-center text-center space-y-4 opacity-20">
                  <Book size={48} strokeWidth={1} />
                  <p className="text-sm font-medium italic">
                    Select a manuscript from the registry to begin mapping.
                  </p>
                </div>
              )}
            </DrashCardContent>
          </DrashCard>

          <DrashButton
            className="w-full py-6 rounded-[2rem] shadow-2xl active:scale-[0.98] text-[11px] tracking-[0.4em]"
            onClick={runIngest}
            disabled={
              !hebrewVersion ||
              stats.status === "fetching" ||
              stats.status === "ingesting"
            }
            isLoading={
              stats.status === "fetching" || stats.status === "ingesting"
            }
          >
            {stats.status === "fetching"
              ? "Synchronizing Mirrors..."
              : "Initiate Dual-Stream Sync"}
          </DrashButton>
        </div>

        <div className="lg:col-span-3 space-y-8">
          <DrashCard
            variant={stats.status === "completed" ? "chaver" : "default"}
            className="p-8 space-y-6"
          >
            <div className="space-y-1">
              <p className="text-[9px] font-black text-zinc-400 uppercase tracking-widest">
                Active Process
              </p>
              <h3 className="text-xl font-black text-zinc-900 tracking-tighter uppercase leading-none">
                {stats.bookTitle || "Idle"}
              </h3>
            </div>

            <div className="space-y-3">
              <div className="flex justify-between text-[10px] font-bold uppercase text-zinc-400 tracking-widest">
                <span>Depth</span>
                <span>
                  {Math.round(
                    (stats.currentProgress / (stats.totalVerses || 1)) * 100
                  )}
                  %
                </span>
              </div>
              <div className="h-3 w-full bg-zinc-100 rounded-full overflow-hidden p-1 shadow-inner relative">
                <div
                  className={cn(
                    "h-full rounded-full transition-all duration-700",
                    stats.status === "completed"
                      ? "bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.5)]"
                      : "bg-zinc-950"
                  )}
                  style={{
                    width: `${
                      (stats.currentProgress / (stats.totalVerses || 1)) * 100
                    }%`,
                  }}
                />
              </div>
            </div>

            {stats.status === "completed" && (
              <div className="p-4 bg-emerald-50 border border-emerald-100 rounded-2xl flex items-center gap-3 text-emerald-700 animate-in zoom-in-95">
                <CheckCircle2 size={16} />
                <span className="text-[10px] font-black uppercase tracking-widest">
                  Logic Synced
                </span>
              </div>
            )}
          </DrashCard>

          <div className="p-8 bg-zinc-900 rounded-[3rem] text-white space-y-6 shadow-2xl">
            <div className="flex items-center justify-between border-b border-white/5 pb-4">
              <h4 className="text-[10px] font-black text-zinc-500 uppercase tracking-[0.3em] flex items-center gap-2">
                <Play size={14} className="text-amber-500" /> Registry Pulse
              </h4>
              <div className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse" />
            </div>
            <div className="space-y-4 font-mono">
              {log.map((entry, i) => (
                <p
                  key={i}
                  className="text-[9px] text-zinc-400 leading-relaxed border-l border-zinc-800 pl-3"
                >
                  {entry}
                </p>
              ))}
              {log.length === 0 && (
                <p className="text-[9px] italic text-zinc-600 pl-3">
                  Ready for cycle...
                </p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
