import {
  AlertCircle,
  CheckCircle2,
  ChevronRight,
  Database,
  Filter,
  Loader2,
  Play,
  Search,
  Trash2,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";

/**
 * DrashX Admin Mission Control: Ingestion Dashboard
 * Allows administrators to search the crawled Sefaria index and trigger
 * row-level ingestion into the Supabase 'library' schema.
 */

const IngestionDashboard = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [crawledData, setCrawledData] = useState([]);
  const [selectedPaths, setSelectedPaths] = useState(new Set());
  const [isIngesting, setIsIngesting] = useState(false);
  const [ingestionLogs, setIngestionLogs] = useState([]);
  const [filterLang, setFilterLang] = useState("all");

  // Simulated fetch of the structured index generated by the crawler
  useEffect(() => {
    const fetchIndex = async () => {
      // In a real environment, this would be an API call to load sefaria_structured_index.json
      // For this UI demo, we simulate the structure based on your crawler's output
      const mockIndex = [
        {
          path: "Commentary/Tanakh/Rashi/Torah/Genesis/English/merged.json",
          parent: "Commentary/Tanakh/Rashi",
          subfolder: "Torah/Genesis",
          book: "Genesis",
          language: "English",
        },
        {
          path: "Commentary/Tanakh/Ramban/Torah/Exodus/Hebrew/merged.json",
          parent: "Commentary/Tanakh/Ramban",
          subfolder: "Torah/Exodus",
          book: "Exodus",
          language: "Hebrew",
        },
        {
          path: "Talmud/Bavli/Seder_Moed/Shabbat/Hebrew/merged.json",
          parent: "Talmud/Bavli/Seder_Moed",
          subfolder: "Shabbat",
          book: "Shabbat",
          language: "Hebrew",
        },
        {
          path: "Tanakh/Torah/Genesis/English/merged.json",
          parent: "Tanakh",
          subfolder: "Torah/Genesis",
          book: "Genesis",
          language: "English",
        },
        // ... more entries would be here
      ];
      setCrawledData(mockIndex);
    };
    fetchIndex();
  }, []);

  // Predictive search and filtering
  const filteredResults = useMemo(() => {
    return crawledData.filter((item) => {
      const matchesSearch =
        item.path.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.book.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesLang =
        filterLang === "all" ||
        item.language.toLowerCase() === filterLang.toLowerCase();
      return matchesSearch && matchesLang;
    });
  }, [searchTerm, crawledData, filterLang]);

  const toggleSelection = (path) => {
    const newSelection = new Set(selectedPaths);
    if (newSelection.has(path)) newSelection.delete(path);
    else newSelection.add(path);
    setSelectedPaths(newSelection);
  };

  const selectAll = () => {
    if (selectedPaths.size === filteredResults.length) {
      setSelectedPaths(new Set());
    } else {
      setSelectedPaths(new Set(filteredResults.map((i) => i.path)));
    }
  };

  const handleStartIngestion = async () => {
    if (selectedPaths.size === 0) return;

    setIsIngesting(true);
    setIngestionLogs([
      {
        type: "info",
        message: `Starting batch ingestion for ${selectedPaths.size} sources...`,
      },
    ]);

    // Simulate the backpressure-aware ingestion process (PRD Section 3)
    for (const path of selectedPaths) {
      setIngestionLogs((prev) => [
        { type: "loading", message: `Processing: ${path}` },
        ...prev,
      ]);
      await new Promise((res) => setTimeout(res, 1500)); // Simulate network/DB latency
      setIngestionLogs((prev) => [
        { type: "success", message: `Successfully ingested ${path}` },
        ...prev,
      ]);
    }

    setIsIngesting(false);
    setSelectedPaths(new Set());
  };

  return (
    <div className="flex flex-col h-screen bg-zinc-50 font-sans text-zinc-900">
      {/* Header */}
      <header className="flex items-center justify-between px-8 py-4 bg-white border-b border-zinc-200 sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-zinc-900 text-white rounded-lg">
            <Database size={20} />
          </div>
          <h1 className="text-xl font-semibold tracking-tight">
            Admin Mission Control
          </h1>
        </div>
        <div className="flex items-center gap-4">
          <div className="text-sm text-zinc-500">
            {crawledData.length} Sources Crawled
          </div>
          <button
            onClick={handleStartIngestion}
            disabled={selectedPaths.size === 0 || isIngesting}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-all ${
              selectedPaths.size > 0 && !isIngesting
                ? "bg-zinc-900 text-white hover:bg-zinc-800"
                : "bg-zinc-100 text-zinc-400 cursor-not-allowed"
            }`}
          >
            {isIngesting ? (
              <Loader2 className="animate-spin" size={18} />
            ) : (
              <Play size={18} />
            )}
            {isIngesting
              ? "Ingesting..."
              : `Ingest Selected (${selectedPaths.size})`}
          </button>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        {/* Main Panel */}
        <main className="flex-1 flex flex-col p-8 overflow-y-auto">
          {/* Controls */}
          <div className="flex flex-col gap-4 mb-8">
            <div className="relative group">
              <Search
                className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-zinc-900 transition-colors"
                size={20}
              />
              <input
                type="text"
                placeholder="Search by book, author, or path (e.g., 'Rashi', 'Genesis')..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-12 pr-4 py-3 bg-white border border-zinc-200 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-zinc-900 transition-all text-lg"
              />
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setFilterLang("all")}
                  className={`px-3 py-1 rounded-full text-sm font-medium ${
                    filterLang === "all"
                      ? "bg-zinc-900 text-white"
                      : "bg-white text-zinc-600 border border-zinc-200"
                  }`}
                >
                  All
                </button>
                <button
                  onClick={() => setFilterLang("English")}
                  className={`px-3 py-1 rounded-full text-sm font-medium ${
                    filterLang === "English"
                      ? "bg-zinc-900 text-white"
                      : "bg-white text-zinc-600 border border-zinc-200"
                  }`}
                >
                  English
                </button>
                <button
                  onClick={() => setFilterLang("Hebrew")}
                  className={`px-3 py-1 rounded-full text-sm font-medium ${
                    filterLang === "Hebrew"
                      ? "bg-zinc-900 text-white"
                      : "bg-white text-zinc-600 border border-zinc-200"
                  }`}
                >
                  Hebrew
                </button>
              </div>
              <button
                onClick={selectAll}
                className="text-sm font-medium text-zinc-600 hover:text-zinc-900"
              >
                {selectedPaths.size === filteredResults.length
                  ? "Deselect All"
                  : "Select All Filtered"}
              </button>
            </div>
          </div>

          {/* Results Grid */}
          <div className="grid grid-cols-1 gap-3">
            {filteredResults.map((item) => (
              <div
                key={item.path}
                onClick={() => toggleSelection(item.path)}
                className={`flex items-center gap-4 p-4 rounded-xl border transition-all cursor-pointer select-none ${
                  selectedPaths.has(item.path)
                    ? "bg-zinc-900 border-zinc-900 text-white shadow-md ring-2 ring-zinc-900 ring-offset-2"
                    : "bg-white border-zinc-200 hover:border-zinc-400"
                }`}
              >
                <div
                  className={`w-6 h-6 rounded-md border-2 flex items-center justify-center transition-colors ${
                    selectedPaths.has(item.path)
                      ? "bg-white border-white"
                      : "border-zinc-200"
                  }`}
                >
                  {selectedPaths.has(item.path) && (
                    <CheckCircle2 className="text-zinc-900" size={16} />
                  )}
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-bold truncate">{item.book}</span>
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] uppercase font-black tracking-widest ${
                        selectedPaths.has(item.path)
                          ? "bg-zinc-700 text-zinc-300"
                          : "bg-zinc-100 text-zinc-500"
                      }`}
                    >
                      {item.language}
                    </span>
                  </div>
                  <div
                    className={`text-xs truncate font-mono mt-0.5 ${
                      selectedPaths.has(item.path)
                        ? "text-zinc-400"
                        : "text-zinc-500"
                    }`}
                  >
                    {item.path}
                  </div>
                </div>

                <div
                  className={`flex items-center gap-1 text-xs font-medium uppercase tracking-tighter ${
                    selectedPaths.has(item.path)
                      ? "text-zinc-400"
                      : "text-zinc-400"
                  }`}
                >
                  {item.parent} <ChevronRight size={14} />
                </div>
              </div>
            ))}

            {filteredResults.length === 0 && (
              <div className="flex flex-col items-center justify-center py-20 text-zinc-400">
                <Filter size={48} className="mb-4 opacity-20" />
                <p className="text-lg">No crawled sources match your search.</p>
              </div>
            )}
          </div>
        </main>

        {/* Side Log Panel */}
        <aside className="w-96 bg-zinc-950 text-zinc-300 border-l border-zinc-800 flex flex-col">
          <div className="p-6 border-b border-zinc-800 flex items-center justify-between">
            <h2 className="text-sm font-bold uppercase tracking-widest text-zinc-500">
              Live Ingestion Log
            </h2>
            <button
              onClick={() => setIngestionLogs([])}
              className="p-1 hover:text-white transition-colors"
            >
              <Trash2 size={16} />
            </button>
          </div>
          <div className="flex-1 overflow-y-auto p-4 font-mono text-xs flex flex-col-reverse gap-2">
            {ingestionLogs.map((log, i) => (
              <div
                key={i}
                className={`flex gap-3 p-3 rounded bg-zinc-900 border-l-2 ${
                  log.type === "success"
                    ? "border-emerald-500 text-emerald-400"
                    : log.type === "loading"
                    ? "border-amber-500 text-amber-400"
                    : log.type === "error"
                    ? "border-rose-500 text-rose-400"
                    : "border-zinc-700"
                }`}
              >
                {log.type === "loading" ? (
                  <Loader2 className="animate-spin flex-shrink-0" size={14} />
                ) : log.type === "success" ? (
                  <CheckCircle2 className="flex-shrink-0" size={14} />
                ) : (
                  <AlertCircle className="flex-shrink-0" size={14} />
                )}
                <span className="break-all">{log.message}</span>
              </div>
            ))}
            {ingestionLogs.length === 0 && (
              <div className="text-center py-10 text-zinc-700 italic">
                Ready to ingest...
              </div>
            )}
          </div>
        </aside>
      </div>
    </div>
  );
};

export default IngestionDashboard;
